services:
  database:
    image: 'mysql:8.0'
    container_name: 'pet_database_service'
    restart: 'always'
    command: 'mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    ports:
      - '3306:3306'
    volumes:
      - './dbdata:/var/lib/mysql'
      - './database.sql:/docker-entrypoint-initdb.dker'
    environment:
      - MYSQL_DATABASE=pet
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - petapp_network

  backend:
    container_name: 'pet_backend_service'
    build:
      context: .
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
      - ./apache-config:/etc/apache2/sites-enabled
    depends_on:
      - database
    networks:
      - petapp_network

networks:
  petapp_network:
    driver: bridge
